@php
    $roleClasses = ['administrador' => 'bg-[#2563EB]/10 text-[#2563EB]', 'medico' => 'bg-[#10B981]/10 text-[#047857]', 'recepcionista' => 'bg-[#38BDF8]/15 text-[#0369A1]', 'caja_finanzas' => 'bg-[#F59E0B]/10 text-[#B45309]'];
@endphp
<x-app-layout><div class="space-y-6">
    <section class="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p class="text-sm font-semibold uppercase tracking-wide text-[#2563EB]">Administración</p><h1 class="mt-2 text-2xl font-bold tracking-tight text-[#0F172A] sm:text-3xl">Usuarios y Roles</h1><p class="mt-2 text-sm text-[#475569]">Gestiona accesos, roles principales y estado del personal de tu clínica.</p></div>@can('users.create')<a href="{{ route('users.create') }}" class="rounded-lg bg-[#2563EB] px-4 py-3 text-center text-sm font-semibold text-white shadow-sm shadow-blue-500/20">Nuevo usuario</a>@endcan</section>
    @if(session('success'))<div class="rounded-lg border border-[#10B981]/20 bg-[#10B981]/10 px-4 py-3 text-sm font-semibold text-[#047857]">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="rounded-lg border border-[#EF4444]/20 bg-[#EF4444]/10 px-4 py-3 text-sm text-[#B91C1C]">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
    <section class="rounded-lg border border-[#E2E8F0] bg-white shadow-sm">
        <form method="GET" action="{{ route('users.index') }}" class="grid gap-4 border-b border-[#E2E8F0] p-5 xl:grid-cols-[1fr_210px_180px_auto]"><div><label for="search" class="mb-2 block text-sm font-semibold">Buscar usuario</label><input id="search" name="search" type="search" value="{{ $search }}" placeholder="Nombre, correo o teléfono" class="w-full rounded-lg border-[#E2E8F0] bg-[#F8FAFC] text-sm focus:border-[#2563EB] focus:ring-[#2563EB]"></div><div><label for="role" class="mb-2 block text-sm font-semibold">Rol</label><select id="role" name="role" class="w-full rounded-lg border-[#E2E8F0] bg-[#F8FAFC] text-sm focus:border-[#2563EB] focus:ring-[#2563EB]"><option value="">Todos</option>@foreach($roles as $value=>$label)<option value="{{ $value }}" @selected($role === $value)>{{ $label }}</option>@endforeach</select></div><div><label for="status" class="mb-2 block text-sm font-semibold">Estado</label><select id="status" name="status" class="w-full rounded-lg border-[#E2E8F0] bg-[#F8FAFC] text-sm focus:border-[#2563EB] focus:ring-[#2563EB]"><option value="">Todos</option><option value="active" @selected($status === 'active')>Activos</option><option value="inactive" @selected($status === 'inactive')>Inactivos</option></select></div><div class="flex items-end gap-2"><button class="h-10 rounded-lg bg-[#0F172A] px-4 text-sm font-semibold text-white">Filtrar</button><a href="{{ route('users.index') }}" class="inline-flex h-10 items-center rounded-lg border border-[#E2E8F0] px-4 text-sm font-semibold text-[#475569]">Limpiar</a></div></form>
        <div class="overflow-x-auto"><table class="min-w-full divide-y divide-[#E2E8F0]"><thead class="bg-[#F8FAFC]"><tr>@foreach(['Nombre','Email','Teléfono','Clínica','Rol','Estado','Creación','Acciones'] as $heading)<th class="px-5 py-3 text-left text-xs font-bold uppercase text-[#475569] {{ $heading === 'Acciones' ? 'text-right' : '' }}">{{ $heading }}</th>@endforeach</tr></thead><tbody class="divide-y divide-[#E2E8F0]">@forelse($users as $managedUser)@php($roleName = $managedUser->getRoleNames()->first())<tr class="hover:bg-[#F8FAFC]"><td class="px-5 py-4 text-sm font-semibold text-[#0F172A]">{{ $managedUser->name }}</td><td class="px-5 py-4 text-sm text-[#475569]">{{ $managedUser->email }}</td><td class="px-5 py-4 text-sm text-[#475569]">{{ $managedUser->phone ?: 'Sin registrar' }}</td><td class="px-5 py-4 text-sm text-[#475569]">{{ $managedUser->clinic?->name }}</td><td class="px-5 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-bold {{ $roleClasses[$roleName] ?? 'bg-slate-100 text-[#475569]' }}">{{ $roles[$roleName] ?? 'Sin rol' }}</span></td><td class="px-5 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-bold {{ $managedUser->status === 'active' ? 'bg-[#10B981]/10 text-[#047857]' : 'bg-slate-100 text-[#475569]' }}">{{ $managedUser->status === 'active' ? 'Activo' : 'Inactivo' }}</span></td><td class="whitespace-nowrap px-5 py-4 text-sm text-[#475569]">{{ $managedUser->created_at?->format('d/m/Y') }}</td><td class="px-5 py-4"><div class="flex justify-end gap-2"><a href="{{ route('users.show',$managedUser) }}" class="rounded-lg border border-[#E2E8F0] px-3 py-2 text-xs font-semibold text-[#2563EB]">Ver</a>@can('users.update')<a href="{{ route('users.edit',$managedUser) }}" class="rounded-lg border border-[#E2E8F0] px-3 py-2 text-xs font-semibold">Editar</a>@endcan @can('users.delete')<form method="POST" action="{{ route('users.destroy',$managedUser) }}" onsubmit="return confirm('¿Eliminar este usuario?');">@csrf @method('DELETE')<button class="rounded-lg border border-[#EF4444]/20 px-3 py-2 text-xs font-semibold text-[#EF4444]">Eliminar</button></form>@endcan</div></td></tr>@empty<tr><td colspan="8">@include('reports._empty-state')</td></tr>@endforelse</tbody></table></div>
        @if($users->hasPages())<div class="border-t border-[#E2E8F0] px-5 py-4">{{ $users->links() }}</div>@endif
    </section>
</div></x-app-layout>
