@php
    $roleName = $managedUser->getRoleNames()->first();
    $roleClasses = ['administrador' => 'bg-[#2563EB]/10 text-[#2563EB]', 'medico' => 'bg-[#10B981]/10 text-[#047857]', 'recepcionista' => 'bg-[#38BDF8]/15 text-[#0369A1]', 'caja_finanzas' => 'bg-[#F59E0B]/10 text-[#B45309]'];
@endphp
<x-app-layout><div class="space-y-6">
    <section class="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p class="text-sm font-semibold uppercase tracking-wide text-[#2563EB]">Detalle del usuario</p><h1 class="mt-2 text-2xl font-bold tracking-tight text-[#0F172A] sm:text-3xl">{{ $managedUser->name }}</h1><p class="mt-2 text-sm text-[#475569]">Información de acceso y rol dentro de MediFlow.</p></div><div class="flex gap-3"><a href="{{ route('users.index') }}" class="rounded-lg border border-[#E2E8F0] px-4 py-3 text-sm font-semibold text-[#475569]">Volver</a>@can('users.update')<a href="{{ route('users.edit',$managedUser) }}" class="rounded-lg bg-[#2563EB] px-4 py-3 text-sm font-semibold text-white">Editar usuario</a>@endcan</div></section>
    @if(session('success'))<div class="rounded-lg border border-[#10B981]/20 bg-[#10B981]/10 px-4 py-3 text-sm font-semibold text-[#047857]">{{ session('success') }}</div>@endif
    <section class="grid gap-6 xl:grid-cols-3"><div class="space-y-6 xl:col-span-2"><article class="rounded-lg border border-[#E2E8F0] bg-white shadow-sm"><div class="border-b border-[#E2E8F0] px-5 py-4"><h2 class="font-bold">Información general</h2></div><div class="grid gap-5 p-5 sm:grid-cols-2"><div><p class="text-xs font-bold uppercase text-[#475569]">Nombre</p><p class="mt-1 text-sm font-semibold">{{ $managedUser->name }}</p></div><div><p class="text-xs font-bold uppercase text-[#475569]">Email</p><p class="mt-1 text-sm">{{ $managedUser->email }}</p></div><div><p class="text-xs font-bold uppercase text-[#475569]">Teléfono</p><p class="mt-1 text-sm">{{ $managedUser->phone ?: 'Sin registrar' }}</p></div><div><p class="text-xs font-bold uppercase text-[#475569]">Clínica</p><p class="mt-1 text-sm">{{ $managedUser->clinic?->name ?? 'Sin clínica' }}</p></div><div><p class="text-xs font-bold uppercase text-[#475569]">Rol actual</p><p class="mt-2"><span class="rounded-full px-2.5 py-1 text-xs font-bold {{ $roleClasses[$roleName] ?? 'bg-slate-100' }}">{{ $roles[$roleName] ?? 'Sin rol' }}</span></p></div><div><p class="text-xs font-bold uppercase text-[#475569]">Estado</p><p class="mt-2"><span class="rounded-full px-2.5 py-1 text-xs font-bold {{ $managedUser->status === 'active' ? 'bg-[#10B981]/10 text-[#047857]' : 'bg-slate-100 text-[#475569]' }}">{{ $managedUser->status === 'active' ? 'Activo' : 'Inactivo' }}</span></p></div></div></article>
        <article class="rounded-lg border border-[#E2E8F0] bg-white p-5 shadow-sm"><h2 class="font-bold">Perfil médico asociado</h2>@if($managedUser->doctor)<p class="mt-2 text-sm text-[#475569]">Este usuario está vinculado al perfil médico de {{ $managedUser->doctor->specialty?->name ?? 'especialidad no registrada' }}.</p><a href="{{ route('doctors.show',$managedUser->doctor) }}" class="mt-4 inline-flex rounded-lg bg-[#2563EB] px-4 py-2.5 text-sm font-semibold text-white">Ver perfil médico</a>@else<p class="mt-2 text-sm text-[#475569]">Este usuario no tiene un perfil médico asociado.</p>@endif</article></div>
        <aside><article class="rounded-lg border border-[#E2E8F0] bg-white shadow-sm"><div class="border-b border-[#E2E8F0] px-5 py-4"><h2 class="font-bold">Fechas</h2></div><div class="space-y-4 p-5"><div><p class="text-xs font-bold uppercase text-[#475569]">Creación</p><p class="mt-1 text-sm">{{ $managedUser->created_at?->format('d/m/Y H:i') }}</p></div><div><p class="text-xs font-bold uppercase text-[#475569]">Actualización</p><p class="mt-1 text-sm">{{ $managedUser->updated_at?->format('d/m/Y H:i') }}</p></div><div><p class="text-xs font-bold uppercase text-[#475569]">Correo verificado</p><p class="mt-1 text-sm">{{ $managedUser->email_verified_at ? 'Sí' : 'No' }}</p></div></div></article></aside></section>
</div></x-app-layout>
