<x-app-layout><div class="space-y-6">
    @include('reports._header', ['title' => 'Reporte clínico', 'description' => 'Actividad médica, cobertura de historiales, diagnósticos, tratamientos y recetas.'])
    @include('reports._filters', ['routeName' => 'reports.clinical', 'showDoctor' => true, 'showPatient' => true])
    <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
        @include('reports._stat-card', ['label' => 'Consultas realizadas', 'value' => number_format($metrics['consultations']), 'tone' => 'green'])
        @include('reports._stat-card', ['label' => 'Recetas emitidas', 'value' => number_format($metrics['prescriptions'])])
        @include('reports._stat-card', ['label' => 'Con historial clínico', 'value' => number_format($metrics['withMedicalRecord']), 'tone' => 'green'])
        @include('reports._stat-card', ['label' => 'Sin historial clínico', 'value' => number_format($metrics['withoutMedicalRecord']), 'tone' => 'yellow'])
        @include('reports._stat-card', ['label' => 'Con alergias registradas', 'value' => number_format($metrics['withAllergies']), 'tone' => 'red'])
        @include('reports._stat-card', ['label' => 'Con enfermedades crónicas', 'value' => number_format($metrics['withChronicDiseases']), 'tone' => 'slate'])
    </section>
    <section class="grid gap-6 xl:grid-cols-2">
        <article class="rounded-lg border border-[#E2E8F0] bg-white p-5 shadow-sm"><h2 class="font-bold text-[#0F172A]">Consultas por médico</h2><div class="mt-4 divide-y divide-[#E2E8F0]">@forelse($consultationsByDoctor as $row)<div class="flex justify-between py-3 text-sm"><span class="font-semibold">{{ $row->doctor?->user?->name ?? 'Sin médico' }}</span><span>{{ $row->total }}</span></div>@empty @include('reports._empty-state') @endforelse</div></article>
        <article class="rounded-lg border border-[#E2E8F0] bg-white p-5 shadow-sm"><h2 class="font-bold text-[#0F172A]">Consultas por paciente</h2><div class="mt-4 divide-y divide-[#E2E8F0]">@forelse($consultationsByPatient as $row)<div class="flex justify-between py-3 text-sm"><span class="font-semibold">{{ $row->patient?->full_name ?? 'Sin paciente' }}</span><span>{{ $row->total }}</span></div>@empty @include('reports._empty-state') @endforelse</div></article>
        <article class="rounded-lg border border-[#E2E8F0] bg-white p-5 shadow-sm"><h2 class="font-bold text-[#0F172A]">Diagnósticos frecuentes</h2><div class="mt-4 divide-y divide-[#E2E8F0]">@forelse($topDiagnoses as $row)<div class="flex justify-between gap-4 py-3 text-sm"><span class="line-clamp-2 text-[#475569]">{{ $row->diagnosis }}</span><span class="font-bold">{{ $row->total }}</span></div>@empty @include('reports._empty-state') @endforelse</div></article>
        <article class="rounded-lg border border-[#E2E8F0] bg-white p-5 shadow-sm"><h2 class="font-bold text-[#0F172A]">Tratamientos frecuentes</h2><div class="mt-4 divide-y divide-[#E2E8F0]">@forelse($topTreatments as $row)<div class="flex justify-between gap-4 py-3 text-sm"><span class="line-clamp-2 text-[#475569]">{{ $row->treatment }}</span><span class="font-bold">{{ $row->total }}</span></div>@empty @include('reports._empty-state') @endforelse</div></article>
    </section>
    <section class="grid gap-6 xl:grid-cols-2">
        <article class="overflow-hidden rounded-lg border border-[#E2E8F0] bg-white shadow-sm"><div class="border-b border-[#E2E8F0] px-5 py-4"><h2 class="font-bold">Últimas consultas</h2></div><div class="divide-y divide-[#E2E8F0]">@forelse($latestConsultations as $consultation)<div class="p-5"><div class="flex flex-wrap justify-between gap-2"><p class="font-semibold">{{ $consultation->patient?->full_name }}</p><p class="text-xs text-[#475569]">{{ $consultation->consultation_date?->format('d/m/Y H:i') }}</p></div><p class="mt-1 text-sm text-[#475569]">{{ $consultation->doctor?->user?->name }}</p><p class="mt-2 line-clamp-2 text-sm">{{ $consultation->diagnosis ?: 'Sin diagnóstico registrado' }}</p></div>@empty @include('reports._empty-state') @endforelse</div></article>
        <article class="overflow-hidden rounded-lg border border-[#E2E8F0] bg-white shadow-sm"><div class="border-b border-[#E2E8F0] px-5 py-4"><h2 class="font-bold">Recetas recientes</h2></div><div class="divide-y divide-[#E2E8F0]">@forelse($recentPrescriptions as $prescription)<div class="p-5"><div class="flex flex-wrap justify-between gap-2"><p class="font-semibold">{{ $prescription->patient?->full_name }}</p><p class="text-xs text-[#475569]">{{ $prescription->prescription_date?->format('d/m/Y') }}</p></div><p class="mt-1 text-sm text-[#475569]">{{ $prescription->doctor?->user?->name }}</p><p class="mt-2 line-clamp-2 text-sm">{{ $prescription->general_instructions ?: 'Sin instrucciones generales' }}</p></div>@empty @include('reports._empty-state') @endforelse</div></article>
    </section>
</div></x-app-layout>
