@php $statusOptions = ['active' => 'Activo', 'inactive' => 'Inactivo']; @endphp
<x-app-layout><div class="space-y-6">
    @include('reports._header', ['title' => 'Reporte de pacientes', 'description' => 'Crecimiento de la base de pacientes, actividad clínica y calidad de información registrada.'])
    @include('reports._filters', ['routeName' => 'reports.patients', 'showStatus' => true])
    <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        @include('reports._stat-card', ['label' => 'Total de pacientes', 'value' => number_format($metrics['total'])])
        @include('reports._stat-card', ['label' => 'Pacientes activos', 'value' => number_format($metrics['active']), 'tone' => 'green'])
        @include('reports._stat-card', ['label' => 'Pacientes nuevos', 'value' => number_format($metrics['new'])])
        @include('reports._stat-card', ['label' => 'Sin historial clínico', 'value' => number_format($metrics['withoutMedicalRecord']), 'tone' => 'yellow'])
        @include('reports._stat-card', ['label' => 'Con historial clínico', 'value' => number_format($metrics['withMedicalRecord']), 'tone' => 'green'])
        @include('reports._stat-card', ['label' => 'Con alergias', 'value' => number_format($metrics['withAllergies']), 'tone' => 'red'])
        @include('reports._stat-card', ['label' => 'Contacto de emergencia', 'value' => number_format($metrics['withEmergencyContact']), 'tone' => 'slate'])
        @include('reports._stat-card', ['label' => 'Pacientes inactivos', 'value' => number_format($metrics['inactive']), 'tone' => 'slate'])
    </section>
    <section class="grid gap-6 xl:grid-cols-2"><article class="rounded-lg border border-[#E2E8F0] bg-white p-5 shadow-sm"><h2 class="font-bold">Pacientes con más citas</h2><div class="mt-4 divide-y divide-[#E2E8F0]">@forelse($topByAppointments as $patient)<div class="flex justify-between py-3 text-sm"><span class="font-semibold">{{ $patient->full_name }}</span><span>{{ $patient->appointments_count }}</span></div>@empty @include('reports._empty-state') @endforelse</div></article><article class="rounded-lg border border-[#E2E8F0] bg-white p-5 shadow-sm"><h2 class="font-bold">Pacientes con más consultas</h2><div class="mt-4 divide-y divide-[#E2E8F0]">@forelse($topByConsultations as $patient)<div class="flex justify-between py-3 text-sm"><span class="font-semibold">{{ $patient->full_name }}</span><span>{{ $patient->consultations_count }}</span></div>@empty @include('reports._empty-state') @endforelse</div></article></section>
    <section class="overflow-hidden rounded-lg border border-[#E2E8F0] bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-[#E2E8F0]"><thead class="bg-[#F8FAFC]"><tr>@foreach(['Paciente','Identificación','Teléfono','Email','Estado','Citas','Consultas','Historial'] as $heading)<th class="px-5 py-3 text-left text-xs font-bold uppercase text-[#475569]">{{ $heading }}</th>@endforeach</tr></thead><tbody class="divide-y divide-[#E2E8F0]">@forelse($patients as $patient)<tr><td class="px-5 py-4 text-sm font-semibold">{{ $patient->full_name }}</td><td class="px-5 py-4 text-sm">{{ $patient->identification_number ?: 'Sin registrar' }}</td><td class="px-5 py-4 text-sm">{{ $patient->phone ?: 'Sin registrar' }}</td><td class="px-5 py-4 text-sm">{{ $patient->email ?: 'Sin registrar' }}</td><td class="px-5 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-bold {{ $patient->status === 'active' ? 'bg-[#10B981]/10 text-[#047857]' : 'bg-slate-100 text-[#475569]' }}">{{ $statusOptions[$patient->status] }}</span></td><td class="px-5 py-4 text-sm font-bold">{{ $patient->appointments_count }}</td><td class="px-5 py-4 text-sm font-bold">{{ $patient->consultations_count }}</td><td class="px-5 py-4 text-sm">{{ $patient->medicalRecord ? 'Sí' : 'No' }}</td></tr>@empty<tr><td colspan="8">@include('reports._empty-state')</td></tr>@endforelse</tbody></table></div><div class="border-t border-[#E2E8F0] px-5 py-4">{{ $patients->links() }}</div></section>
</div></x-app-layout>
