/**
 * Generates random data for creating a patient.
 */
export function createUniquePatientData() {
  const timestamp = Date.now();
  return {
    first_name: `E2E_First_${timestamp}`,
    last_name: `E2E_Last_${timestamp}`,
    email: `patient_${timestamp}@example.com`,
    phone: `09${Math.floor(Math.random() * 100000000).toString().padStart(8, '0')}`,
    birth_date: '1990-01-01',
    address: 'E2E Test Address',
    identification_number: Math.floor(Math.random() * 10000000000).toString().padStart(10, '0'), // 10 digit ID
    gender: 'otro',
  };
}

/**
 * Generates random data for an appointment.
 */
export function createUniqueAppointmentData() {
  return {
    reason: `E2E Consultation Reason ${Date.now()}`,
    notes: 'Generated by E2E test'
  };
}
